MESSAGES_DEFAULT_LIMIT = 50
MESSAGES_DEFAULT_OFFSET = 0

PHONE_NUMBER_REGULAR_PATTERN = r'^\+\d{8,15}$'
MIN_USERNAME_LENGTH = 5
MAX_USERNAME_LENGTH = 32
MIN_ABOUT_ME_LENGTH = 1
MAX_ABOUT_ME_LENGTH = 256
